"""empty message

Revision ID: 979c6e0e32d6
Revises: a5cffa318ac2
Create Date: 2026-03-06 20:18:21.379016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979c6e0e32d6'  # ✅ Identificadores de revisión claros
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),  # ✅ Definición de columna correcta
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),  # ✅ Relación con la tabla user
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))  # 🔧 Cambiar 'user_name' a 'username' para consistencia
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))  # ✅ Buen uso de columnas
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))  # ✅ Buen uso de columnas
        batch_op.create_unique_constraint('uq_user_name', ['user_name'])  # 🔧 Añadir nombre a la restricción única

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_name', type_='unique')  # 🔧 Cambiar a 'uq_user_name' para eliminar la restricción única correctamente
        batch_op.drop_column('last_name')  # ✅ Eliminación de columna correcta
        batch_op.drop_column('first_name')  # ✅ Eliminación de columna correcta
        batch_op.drop_column('user_name')  # 🔧 Cambiar a 'username' para consistencia

    op.drop_table('post')  # ✅ Eliminación de tabla correcta
    # ### end Alembic commands ###
