"""empty message

Revision ID: e95a8f4f624e
Revises: 5f92407748da
Create Date: 2026-03-08 12:46:49.573891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95a8f4f624e'  # ✅ Identificador de revisión correcto
 down_revision = '5f92407748da'  # ✅ Identificador de revisión anterior correcto
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),  # ✅ Definición de columna correcta
    sa.Column('comment_text', sa.String(length=500), nullable=False),  # ✅ Definición de columna correcta
    sa.Column('author_id', sa.Integer(), nullable=False),  # ✅ Definición de columna correcta
    sa.Column('post_id', sa.Integer(), nullable=False),  # ✅ Definición de columna correcta
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),  # ❌ Error: 'user.id' debe ser 'user.id' (nombre de tabla correcto)
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),  # ❌ Error: 'post.id' debe ser 'post.id' (nombre de tabla correcto)
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')  # ✅ Eliminación de tabla correcta
    # ### end Alembic commands ###
